controller_joint_names: ['', 'left_wheel', 'Right_wheel', ]
simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_wheel_trans:
    type: effort_controllers/JointVelocityController
    joint: left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_wheel_trans:
    type: velocity_controllers/JointVelocityController
    joint: Right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}